# Generated by Django 4.1.7 on 2023-02-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="caption",
            field=models.TextField(blank="", default=""),
        ),
        migrations.AddField(
            model_name="feed",
            name="comment_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="feed",
            name="img",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
