# Generated by Django 4.1.7 on 2023-02-21 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0004_rename_comment_count_feed_likes_count_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feed",
            old_name="reivews_count",
            new_name="reviews_count",
        ),
    ]
