# Generated by Django 4.1.7 on 2023-02-27 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feeds", "0005_rename_reivews_count_feed_reviews_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feeds",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
