# Generated by Django 4.1.7 on 2023-02-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_review_created_review_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="payload",
            new_name="caption",
        ),
    ]
